pipeline {
    agent any

    environment {
        // This will create POSTGRES_SECRET_USR and POSTGRES_SECRET_PSW environment variables
        POSTGRES_SECRET = credentials('jenkins-postgres-credentials')
    }

    stages {
        stage('Install Dependencies') {
            steps {
                sh 'pwd'
                sh 'ls -l'
                sh 'ls -l "PyTest DQ Framework"'
                sh 'python3 -m venv .venv'
                sh '. .venv/bin/activate && pip install -r "PyTest DQ Framework/requirements.txt"'
            }
        }

        stage('Run Pytest') {
            steps {
                // Make sure the html_report directory exists before running pytest
                sh '''
                    . .venv/bin/activate
                    cd "PyTest DQ Framework"
                    mkdir -p "html_report"
                    pytest tests -m "parquet_data" \
                        --db_host="postgres" \
                        --db_port="5432" \
                        --db_name="mydatabase" \
                        --db_user="$POSTGRES_SECRET_USR" \
                        --db_password="$POSTGRES_SECRET_PSW" \
                        --html="PyTest DQ Framework/html_report/index.html"
                '''
                sh 'ls -l "PyTest DQ Framework/html_report"'
            }
        }

        stage('Archive Test Report') {
            steps {
                // Archive the entire html_report directory, including assets
                archiveArtifacts artifacts: 'PyTest DQ Framework/html_report/**', allowEmptyArchive: true

                // Publish the HTML report
                publishHTML(target: [
                            allowMissing: false,  // Fail the pipeline if the report is missing
                            keepAll: true,        // Keep all reports from previous runs
                            reportDir: 'PyTest DQ Framework/html_report', // Correct directory path
                            reportFiles: 'index.html',                          // Entry point file
                            reportName: 'HTML Test Report'                      // Display name in Jenkins
                ])
            }
        }
}