[tool:pytest]
rp_endpoint = https://reportportal.epam.com/api/v1
rp_uuid = dq-auto_WdRZ8QEXT6aTJT48QMyhtbsUAbR1N3aQSxsJUObz9syc8nn2_-Zfuv_qsHcR_kOg
rp_project = regina_khvan_personal
rp_launch = My_First_Launch
rp_api_retries = 1
rp_log_level = DEBUG

# marks
markers = 
            validate_csv: marks tests related to valitation of validate_csv        
# python_files
python_files=test_*.py
